<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.hKRIg8x' shared service.

return $this->privates['.service_locator.hKRIg8x'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\WildController::index' => ['privates', '.service_locator.58Rml10', 'get_ServiceLocator_58Rml10Service.php', true],
    'App\\Controller\\WildController::show' => ['privates', '.service_locator.58Rml10', 'get_ServiceLocator_58Rml10Service.php', true],
    'App\\Controller\\WildController::showByCategory' => ['privates', '.service_locator.a.laFVK', 'get_ServiceLocator_A_LaFVKService.php', true],
    'App\\Controller\\WildController:index' => ['privates', '.service_locator.58Rml10', 'get_ServiceLocator_58Rml10Service.php', true],
    'App\\Controller\\WildController:show' => ['privates', '.service_locator.58Rml10', 'get_ServiceLocator_58Rml10Service.php', true],
    'App\\Controller\\WildController:showByCategory' => ['privates', '.service_locator.a.laFVK', 'get_ServiceLocator_A_LaFVKService.php', true],
], [
    'App\\Controller\\WildController::index' => '?',
    'App\\Controller\\WildController::show' => '?',
    'App\\Controller\\WildController::showByCategory' => '?',
    'App\\Controller\\WildController:index' => '?',
    'App\\Controller\\WildController:show' => '?',
    'App\\Controller\\WildController:showByCategory' => '?',
]);
