#index:
#    path: /
#    controller: App\Controller\DefaultController::index

# config/routes.yaml

# the "wild_index" route name is not important yet
wild_show:
  path: /wild/
  controller: App\Controller\WildController::show
  #controller: App\Controller\DefaultController::index

wild_index:
  path: /wild
  controller: App\Controller\WildController::index