<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDLKaI1x\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDLKaI1x/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerDLKaI1x.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerDLKaI1x\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerDLKaI1x\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'DLKaI1x',
    'container.build_id' => 'aec00d4b',
    'container.build_time' => 1576489025,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDLKaI1x');
