<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUx9gOmu\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUx9gOmu/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUx9gOmu.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUx9gOmu\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerUx9gOmu\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'Ux9gOmu',
    'container.build_id' => 'a1cb589d',
    'container.build_time' => 1575905055,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUx9gOmu');
