<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSdvmfYg\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSdvmfYg/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSdvmfYg.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSdvmfYg\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerSdvmfYg\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'SdvmfYg',
    'container.build_id' => 'fdab2e31',
    'container.build_time' => 1575971709,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSdvmfYg');
